[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
hedwig_sol = "H4J9wWhraK2Zvn4o9aFheFVmAf7nfaBNPw3d7w77X1eC"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
